name: CFFormat

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
  pull_request:
    branches:
      - main
      - master
      - development
    # Only run if *.cfc files are modified
    paths:
      - '**.cfc'

jobs:
  format1:
    name: CFFormat Installed In Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Set Up CommandBox
        uses: elpete/setup-commandbox@v1.0.0

      - name: Install CFFormat
        run: box install commandbox-cfformat

      - name: Run CFFormat
        run: box cfformat run path=models,handlers,interceptors,tests/specs --overwrite
  format2:
    name: CFFormat With Reusable GitHub Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run CFFormat
        uses: michaelborn/commandbox-action@v1
        with:
          cmd: cfformat run path=models,tests/specs --overwrite

      - name: Commit Format Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "👌 IMPROVE: Auto-format cfcs via cfformat"